import { renameSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import type {
  ContentItem,
  ContentSummary,
  SummarizerProvider,
  UserProfile,
} from "@looplia-core/core";

import type { ClaudeAgentConfig, ProviderResultWithUsage } from "./config";
import { writeContentItem } from "./content-io";
import { executeAgenticQuery } from "./utils/query-wrapper";
import { SUMMARY_OUTPUT_SCHEMA } from "./utils/schema-converter";
import { ensureWorkspace, writeUserProfile } from "./workspace";

// Regex patterns for ID generation
const WHITESPACE_PATTERN = /\s+/;
const INVALID_ID_CHARS_PATTERN = /[^a-z0-9-]/g;
const MULTIPLE_DASHES_PATTERN = /--+/g;

/**
 * Generate meaningful ID based on detected source and content characteristics
 */
function generateMeaningfulId(summary: ContentSummary): string {
  const source = summary.detectedSource || "text";
  const date = new Date().toISOString().split("T")[0]; // YYYY-MM-DD

  // Extract topic from headline or first keyTheme
  let topic = "content";
  if (summary.headline) {
    // Take first 2-3 words from headline, lowercase, hyphen-separated
    const words = summary.headline
      .toLowerCase()
      .split(WHITESPACE_PATTERN)
      .slice(0, 2);
    topic = words.join("-").replace(INVALID_ID_CHARS_PATTERN, "");
  } else if (summary.keyThemes?.[0]) {
    topic = summary.keyThemes[0].toLowerCase().replace(WHITESPACE_PATTERN, "-");
  }

  // Generate ID: source-date-topic
  return `${source}-${date}-${topic}`
    .replace(MULTIPLE_DASHES_PATTERN, "-")
    .slice(0, 60);
}

/**
 * Build agentic prompt for summarization (v0.3.1 approach)
 *
 * The agent:
 * 1. Reads CLAUDE.md for full task instructions
 * 2. Invokes content-analyzer subagent via Skill
 * 3. Reads the generated summary.json output file
 * 4. Returns the JSON as structured output
 *
 * Content is stored in flat folder: contentItem/{id}/
 * - content.md: original content to process
 * - summary.json: generated by content-analyzer subagent
 */
function buildMinimalSummarizePrompt(contentId: string): string {
  return `Task: Analyze and summarize content.

Use the content-analyzer subagent to process: contentItem/${contentId}/content.md

The subagent will:
1. Read content from contentItem/${contentId}/content.md
2. Perform deep analysis using skills
3. Write results to contentItem/${contentId}/summary.json

After the subagent completes, read contentItem/${contentId}/summary.json and return its contents as the structured output.`;
}

/**
 * Claude-powered summarizer provider
 *
 * Uses Claude Agent SDK to analyze content and generate structured summaries
 * with headlines, TL;DRs, bullets, tags, and relevance scores.
 */
export type ClaudeSummarizerProvider = SummarizerProvider & {
  /**
   * Summarize content with usage metrics
   */
  summarizeWithUsage(
    content: ContentItem,
    user?: UserProfile
  ): Promise<ProviderResultWithUsage<ContentSummary>>;
};

/**
 * Create a Claude-powered summarizer provider
 *
 * @param config - Optional configuration overrides
 * @returns SummarizerProvider implementation using Claude Agent SDK
 *
 * @example
 * ```typescript
 * const summarizer = createClaudeSummarizer({
 *   model: "claude-haiku-4-5-20251001",
 *   workspace: "~/.looplia"
 * });
 *
 * const result = await summarizer.summarize(content, user);
 * if (result.success) {
 *   console.log(result.data.headline);
 * }
 * ```
 */
export function createClaudeSummarizer(
  config?: ClaudeAgentConfig
): ClaudeSummarizerProvider {
  return {
    summarize(content, user) {
      return this.summarizeWithUsage(content, user);
    },

    async summarizeWithUsage(content, user) {
      // Ensure workspace exists and get path
      const workspace = await ensureWorkspace({
        baseDir: config?.workspace,
      });

      // Write content item to workspace
      await writeContentItem(content, workspace);

      // Write user profile if provided
      if (user) {
        await writeUserProfile(workspace, user);
      }

      // Build minimal prompt - agent reads CLAUDE.md for full instructions
      const prompt = buildMinimalSummarizePrompt(content.id);

      // Execute agentic query with workspace context
      const result = await executeAgenticQuery<ContentSummary>(
        prompt,
        SUMMARY_OUTPUT_SCHEMA,
        {
          ...config,
          workspace,
        }
      );

      // Persist summary and handle ID generation
      if (result.success) {
        const tempDir = join(workspace, "contentItem", content.id);
        const summaryPath = join(tempDir, "summary.json");
        writeFileSync(
          summaryPath,
          JSON.stringify(result.data, null, 2),
          "utf-8"
        );

        // Generate meaningful ID based on detected source
        const meaningfulId = generateMeaningfulId(result.data);

        // If ID changed, relocate the content folder
        if (meaningfulId !== content.id) {
          const newDir = join(workspace, "contentItem", meaningfulId);
          try {
            renameSync(tempDir, newDir);

            // Update the contentId in the returned data
            result.data.contentId = meaningfulId;

            // Re-write summary with new contentId
            writeFileSync(
              join(newDir, "summary.json"),
              JSON.stringify(result.data, null, 2),
              "utf-8"
            );
          } catch (error) {
            // If relocation fails, keep original ID
            console.warn(
              `Failed to relocate content from ${content.id} to ${meaningfulId}:`,
              error
            );
          }
        }
      }

      return result;
    },
  };
}
