import { renameSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import type {
  ContentItem,
  ContentSummary,
  SummarizerProvider,
  UserProfile,
} from "@looplia-core/core";

import type { ClaudeAgentConfig, ProviderResultWithUsage } from "./config";
import { writeContentItem } from "./content-io";
import { executeAgenticQuery } from "./utils/query-wrapper";
import { SUMMARY_OUTPUT_SCHEMA } from "./utils/schema-converter";
import { ensureWorkspace, writeUserProfile } from "./workspace";

/**
 * Build agentic prompt for summarization (v0.3.1 approach)
 *
 * The agent:
 * 1. Reads CLAUDE.md for full task instructions
 * 2. Invokes content-analyzer subagent via Skill
 * 3. Reads the generated summary.json output file
 * 4. Returns the JSON as structured output
 *
 * Content is stored in flat folder: contentItem/{id}/
 * - content.md: original content to process
 * - summary.json: generated by content-analyzer subagent
 */
function buildMinimalSummarizePrompt(contentId: string): string {
  return `Task: Analyze and summarize content.

Use the content-analyzer subagent to process: contentItem/${contentId}/content.md

The subagent will:
1. Read content from contentItem/${contentId}/content.md
2. Perform deep analysis using skills
3. Write results to contentItem/${contentId}/summary.json

After the subagent completes, read contentItem/${contentId}/summary.json and return its contents as the structured output.`;
}

/**
 * Claude-powered summarizer provider
 *
 * Uses Claude Agent SDK to analyze content and generate structured summaries
 * with headlines, TL;DRs, bullets, tags, and relevance scores.
 */
export type ClaudeSummarizerProvider = SummarizerProvider & {
  /**
   * Summarize content with usage metrics
   */
  summarizeWithUsage(
    content: ContentItem,
    user?: UserProfile
  ): Promise<ProviderResultWithUsage<ContentSummary>>;
};

/**
 * Create a Claude-powered summarizer provider
 *
 * @param config - Optional configuration overrides
 * @returns SummarizerProvider implementation using Claude Agent SDK
 *
 * @example
 * ```typescript
 * const summarizer = createClaudeSummarizer({
 *   model: "claude-haiku-4-5-20251001",
 *   workspace: "~/.looplia"
 * });
 *
 * const result = await summarizer.summarize(content, user);
 * if (result.success) {
 *   console.log(result.data.headline);
 * }
 * ```
 */
export function createClaudeSummarizer(
  config?: ClaudeAgentConfig
): ClaudeSummarizerProvider {
  return {
    summarize(content, user) {
      return this.summarizeWithUsage(content, user);
    },

    async summarizeWithUsage(content, user) {
      // Ensure workspace exists and get path
      const workspace = await ensureWorkspace({
        baseDir: config?.workspace,
      });

      // Write content item to workspace
      await writeContentItem(content, workspace);

      // Write user profile if provided
      if (user) {
        await writeUserProfile(workspace, user);
      }

      // Build minimal prompt - agent reads CLAUDE.md for full instructions
      const prompt = buildMinimalSummarizePrompt(content.id);

      // Execute agentic query with workspace context
      const result = await executeAgenticQuery<ContentSummary>(
        prompt,
        SUMMARY_OUTPUT_SCHEMA,
        {
          ...config,
          workspace,
        }
      );

      // Persist summary and handle ID generation using SDK session ID
      if (result.success && result.sessionId) {
        const tempDir = join(workspace, "contentItem", content.id);
        const sessionId = result.sessionId;

        // Use SDK session ID as folder name for guaranteed uniqueness
        const newDir = join(workspace, "contentItem", sessionId);

        try {
          // Relocate content folder to use SDK session ID
          renameSync(tempDir, newDir);

          // Update the contentId in the returned data
          result.data.contentId = sessionId;

          // Write summary with session ID
          const summaryPath = join(newDir, "summary.json");
          writeFileSync(
            summaryPath,
            JSON.stringify(result.data, null, 2),
            "utf-8"
          );
        } catch (error) {
          // If relocation fails, write to original location
          console.warn(
            `Failed to relocate content from ${content.id} to ${sessionId}:`,
            error
          );
          const summaryPath = join(tempDir, "summary.json");
          writeFileSync(
            summaryPath,
            JSON.stringify(result.data, null, 2),
            "utf-8"
          );
        }
      } else if (result.success) {
        // Fallback: no session ID, write to original location
        const tempDir = join(workspace, "contentItem", content.id);
        const summaryPath = join(tempDir, "summary.json");
        writeFileSync(
          summaryPath,
          JSON.stringify(result.data, null, 2),
          "utf-8"
        );
      }

      return result;
    },
  };
}
